(define (curry f)
	(lambda (a)
		(lambda (b)
			(lambda (c)
				(lambda (d)
					(f a b c d)
				)
			)
		)
	)
)

(define (main) 
	(setPort (open (getElement ScamArgs 1) 'read))
    (define f (eval (readExpr) this))
	(define x1 (readExpr))
	(define x2 (readExpr))
	(define x3 (readExpr))
	(define x4 (readExpr))
	(println "(((((curry " f ") " x1 ") " x2 ") " x3 ") " x4 ") is "(((((curry f) x1) x2) x3) x4))
)