(define (ramanujanr n)
	((lambda (x) 
		(* n n)
	) (+ 1 n))
)

(define (main)
	;(setPort (open (getElement ScamArgs 1) 'read))
    ;(define n (readInt))
	(define n (int (getElement ScamArgs 1)))
	(println "(ramanujanr " n ") is " (fmt "%.25f" (ramanujanr n)))
	(println "$4$")
)