(define (replace obj replacements)
	(define (replaceSymbol sym replacements)
		(if (or (not (symbol? sym)) (nil? replacements))
			sym
			(if (== sym (car replacements))
				(car (cdr replacements))
				(replaceSymbol sym (cdr replacements))
			)
		)
	)
	(cond
		((function? obj)
			(set 'code (replace (get 'code obj) replacements) obj)
		)
		((or (nil? obj) (object? obj))
			obj
		)
		((list? obj)
			(cons (replace (car obj) replacements) (replace (cdr obj) replacements))
		)
		((symbol? obj)
			(replaceSymbol obj replacements)
		)
		(else obj)
	)
)

(define (main)
	(setPort (open (getElement ScamArgs 1) 'read))
	(define env this)
    (define (iter expr)
         (if (not (eof?)) (begin (eval expr env) (iter (readExpr))))
         )
    (iter (readExpr))
)